//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.21 at 05:09:20 AM EAT 
//


package com.sira.dto.employer;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlSchemaType;


public class EmployerProfileDto {

    public BigInteger onTime;
    public BigInteger onBudget;
    public BigInteger repeatHire;
    public BigInteger reviews;
    @XmlSchemaType(name = "integer")
    public Integer star;
    public String title;

}
